language: php
php:
  - "5.4"
before_script:
  - phpenv global system
  - rm -rf cookbooks/percona
  - sudo chef-solo -c config/solo.rb -j config/node.json
  - bundle install
  - bundle exec cucumber --quiet --no-source tests/bakery/features || true
script:
  - bundle exec cucumber --no-source tests/bakery/features
notifications:
  email: false
